name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # The workflow will trigger on pushes to the main branch

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint  # Run this job after linting succeeds
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: test  # Run this job after testing succeeds
    steps:
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'account-microservice-webapp'  # Matches the "msdeploySite" in your publish profile
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Ensure this secret contains the publish profile XML content
        package: .  # This deploys the entire repository; adjust if needed